config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
  end
  get 'about', to: 'pages#about'
  resources :contacts, only: :create 
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  
  # Contact form validations
  validates :name, presence: true
  validates :email, presence: true
  validates :comments, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
    has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    belongs_to :user
    
    has_attached_file :avatar, 
                      :styles => { :medium => "300x00>", :thumb => "100x100>" },
                      :default_url => "images/:style/missing.png"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  belongs_to :plan
  has_one :profile
  
  # Extend Devise user registrations so that pro users save with special stripe
  # Otherwise, Devise saves as usual
  attr_accessor :stripe_card_token
  
  def save_with_subscription
  # If pro users pass validations, call Stripe and have it set a monthly subscription 
  # Stripe responds with customer data and we store in the DB
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, source: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
 # Whitelist form fields 
  protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:stripe_card_token, :email, :password, :password_confirmation)}
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
   # GET request to /contact-us
   # Show new form (empty)
   def new
      @contact = Contact.new
   end
   
   # POST request /contacts
   def create
      # Mass asignment to @contact instance variable
      @contact = Contact.new(contact_params)
      
      # Save the Contact object parameters to @contact
      if @contact.save
         # Store form fields via params, into variables
         name = params[:contact][:name]
         email = params[:contact][:email]
         body = params[:contact][:comments]
         # Plug variables into ContactMailer, email method and send email
         ContactMailer.contact_email(name, email, body).deliver
         
         flash[:success] = "Mensaje enviado. Muchas gracias."
         redirect_to new_contact_path
      else
         # If Contact object doesn't save, store errors in flash-hash
         flash[:danger] = "Ocurrió un error: " + @contact.errors.full_messages.join(", ")
         redirect_to new_contact_path
      end
   end 
      
   # Use strong parameters to white list form fields
   private 
      def contact_params
         params.require(:contact).permit(:name, :email, :comments)
      end
   
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @basic_plan = Plan.find(1)
    @pro_plan = Plan.find(2)
  end
  
  def about
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!
    before_action :only_current_user

    
    
    def new
        # GET -> Render blank profile form
        @profile = Profile.new
    end
    
    def create
        # POST -> Creates or updates profile to /users/:user_id/profile
        # Ensure the user is building the profile
        @user = User.find(params[:user_id])
        @profile = @user.build_profile( profile_params )
        if @profile.save
            flash[:success] = "Perfil actualizado"
            redirect_to user_path( params[:user_id] )
        else
            render action: :new
        end
    end
    
    #GET request for users/:user_id/profile/edit
    def edit
        @user = User.find(params[:user_id])
        @profile = @user.profile
    end
    
    #PUT to /users/:user_id/profile
    def update
        @user = User.find(params[:user_id])
        @profile = @user.profile
        if @profile.update_attributes(profile_params)
            flash[:success] = "Perfil actualizado!"
            redirect_to user_path(id: params[:user_id])
        else
            render action: :edit
        end
    end
    
    private
        def profile_params
        params.require(:profile).permit(:first_name, :last_name, :avatar, :job_title, :phone_number, :contact_email, :description)
        end
        
        def only_current_user
            @user = User.find(params[:user_id])
            redirect_to(root_url) unless @user == current_user
        end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    before_action :select_plan, only: :new
    
    def create
        super do |resource|
            if params[:plan]
                resource.plan_id = params[:plan]
                if resource.plan_id == 2
                    resource.save_with_subscription
                else
                    resource.save
                end
            end
        end
    end
    
    private
    
    def select_plan
        unless (params[:plan] == '1' or params[:plan] == '2')
            flash[:notice] = "Por favor, seleccione un plan válido"
            redirect_to root_url
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

    # GET action for /users/:id
    def show
        @user = User.find( params[:id])
    end
    
    def index
    
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def job_title_icon
        if @user.profile.job_title == "Desarrollador"
            "<i class='fa fa-code'></i>".html_safe
        elsif @user.profile.job_title == "Emprendedor"
            "<i class='fa fa-lightbulb-o'></i>".html_safe
        elsif @user.profile.job_title == "Inversor"
            "<i class='fa fa-dollar'></i>".html_safe
        end
    end
end

app/views/contacts/new.html.erb
<div class="container">
    <div class="row">
        <h3 class="text-center">Contáctenos</h3>
       
       <div class="col-md-6 col-md-offset-3">
           <div class="well">
               <%= form_for @contact do |f| %>
                   <div class="form-group">
                       <%= f.label :nombre %>
                       <%= f.text_field :name, class: 'form-control' %>
                   </div>
                   
                   <div class="form-group">
                       <%= f.label :email %>
                       <%= f.text_field :email, class: 'form-control' %>
                   </div>
                   
                   <div class="form-group">
                       <%= f.label :comentarios  %>
                       <%= f.text_area :comments, class: 'form-control' %>
                   </div>
                   <%= f.submit "Enviar", class: 'btn btn-default' %>
               <% end %>
           </div>
        
       </div>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE
 html>
<html>
  <head>
    <title>DevMatch</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <%= tag :meta, :name => 'stripe-key', :content => STRIPE_PUBLIC_KEY %> 
    
  </head>

  <body>
    
    <!-- NavBar -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            <i class="fa fa-group"></i> 
            Dev<span class="match">Match</span>
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <div class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <%= link_to "Salir", destroy_user_session_path, method: :delete, class: "btn btn-primary navbar-btn" %>
            <% else %>
              <%= link_to "Ingresar", new_user_session_path, class: "btn btn-primary navbar-btn" %>
            <% end %>
          </div>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Acerca", about_path %></li>
            <li><%= link_to "Contacto", new_contact_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    
    <div class="container flash-container">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{type}" %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container text-center">
  <h1>Acerca de...</h1>
  <p>Somos <i class="fa fa-group"></i> DevMatch. Nuestra compañía provee espacios
  flexibles y exclusivos para que desarrolladores y emprendedores se puedan
  encontrar para crear juntos sus sueños</p>
</div>

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid">
  <h1>Bienvenido a DevMatch</h1>
  <h3>Donde emprendedores y desarrolladores se encuentran.</h3>
</div>

<div class="container text-center home-signup-links">
    <div class="row">
      <% if user_signed_in? %>
        <div class="col-md-6">
          <div class="well">
            <h2 class="text-center">Tu perfil DevMatch</h2>    
            <% if current_user.profile %>
              <%= link_to "Editar perfil",edit_user_profile_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
              <%= link_to "Ver perfil", user_path(id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
            <% else %>
              <p>Crea tu perfil para contactar con la comunidad</p>
              <%= link_to '¡Crea tu perfil!', new_user_profile_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
            <% end %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="well">
            <h2 class="text-center">Conocé la comunidad DevMatch</h2>
            <p> Contactá con otros desarrolladores, emprendedores e inversores</p>
            <%= link_to "Conocer la comunidad", users_path, class: 'btn btn-default btn-lg btn-block' %>
          </div>
        </div>
    
      <% else %>
      
        <div class="col-md-6">
          <div class="well">    
            <h2> Registrarse en el Plan Básico</h2>
            <h4> Acceso a la comunidad DevMatch</h4>
            <%= link_to "Acceso Básico", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-primary btn-lg btn-block' %>
        </div>
        </div>
          <div class="col-md-6">
            <div class="well">
            <h2> Registrarse en el Plan Pro</h2>
            <h4> Acceso a la comunidad DevMatch y datos de contacto</h4>
            <%= link_to "Acceso Pro",new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-success btn-lg btn-block' %>
          </div>
        </div>
      
    <% end %>
  </div>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, :html => { :multipart => true } do |f| %>
    
    <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :avatar %>
        <%= f.file_field :avatar, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :job_title %>
        <%= f.select :job_title, ['Desarrollador', 'Emprendedor', 'Inversor'], {}, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :contact_email %>
        <%= f.text_field :contact_email, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.submit "Actualizar perfil", class: 'btn btn-primary' %>
    </div>

<% end %>

app/views/profiles/edit.html.erb
<div class="container"></div>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1 class="text-center">Edita tu perfil</h1>
            <p class="text-center">Sé parte de la comunidad de DevMatch</p>
            <div class="well">
                <%= render 'form' %>
            </div>
        </div>
    </div>
</div>

app/views/profiles/new.html.erb
<div class="container"></div>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1 class="text-center">Crea tu perfil</h1>
            <p class="text-center">Sé parte de la comunidad de DevMatch</p>
            <div class="well">
                <%= render 'form' %>
            </div>
        </div>
    </div>
</div>

app/views/users/index.html.erb
List of all users

app/views/users/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <%= image_tag @user.profile.avatar.url, class: 'avatar-show-img' %>
        </div>
        <div class="col-md-6">
            <h1><%= @user.profile.first_name %> <%= @user.profile.last_name %><br/></h1>
            <h3><span class="job-title-icon"><%= job_title_icon %></span><%= @user.profile.job_title %></h3><br/>
            <div class="well profile-block profile-description">
                <h3>Descripción</h3>
                <%= @user.profile.description %>
            </div>
            <% if current_user.plan_id == 2 %>
                <div class="well profile-block profile-contact-info">
                    <h3>Información de contacto</h3>
                    <%= @user.profile.contact_email %><br/>
                    <%= @user.profile.phone_number %>
                </div>
            <% end %>
        </div>
    </div>
</div>